name: CD

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Deploy locally on VPS
        run: |
          cd /home/wigamu/wgsoft
          git pull
          # Workaround for docker-compose v1 ContainerConfig bug
          docker rm -f wgsoft-frontend wgsoft-backend || true
          cd /home/wigamu/wgsoft/infra
          docker-compose up -d --build
