name: CD

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Deploy locally on VPS
        run: |
          cd /home/wigamu/wgsoft
          git pull
          # Clean old containers to avoid name conflicts
          cd /home/wigamu/wgsoft/infra
          docker compose down --remove-orphans || true
          docker rm -f wgsoft-db wgsoft-backend wgsoft-frontend || true
          docker compose up -d --build
